name: Update Multiverse Tracker Data

on:
  repository_dispatch:
    types: [update-world-field]

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure Git Authentication
      - name: Configure Git Authentication
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/RebelPilotTyler/multiverse_tracker.git

      # Step 3: Update worlds.json
      - name: Update worlds.json
        run: |
          echo '${{ github.event.client_payload }}' > payload.json
          worldIndex=$(jq -r '.worldIndex' payload.json)
          key=$(jq -r '.key' payload.json)
          newValue=$(jq -r '.newValue' payload.json)
          jq '.[${worldIndex}] |= setpath([\"$(echo $key | tr '.' '\", \"')\"]; \"$newValue\")' worlds.json > temp.json
          mv temp.json worlds.json
          git add worlds.json
          git commit -m "Updated field $key for world index $worldIndex"
          git push
      - name: Debug Payload
        run: |
          echo "worldIndex=$worldIndex"
          echo "key=$key"
          echo "newValue=$newValue"
          cat worlds.json

        